export const FILTER_ITEMS_BY_PRICE = 'FILTER_ITEMS_BY_PRICE';
export const FILTER_ITEMS_BY_PRICE_SUCCESS = 'FILTER_ITEMS_BY_PRICE_SUCCESS';
export const FILTER_ITEMS_BY_PRICE_FAIL = 'FILTER_ITEMS_BY_PRICE_FAIL';